

interface DayPlan {
    date: string;
    bvMenu: Menu;
    meatlessMenu: Menu;
    dinner: string;
    dessert?: Menu;
}

interface WeekPlan {
    weekNumber: number;
    year: number;
    days: DayPlan[];
}

interface Menu {
    id: string; //generated by firebase
    name: string;
    description?: string;
    price?: number;
    amount: number;
  }


let weekPlans = [
    {
        weekNumber: 33,
        year: 2024,
        days: [
            {
                date: '2024-08-12',
                bvMenu: {
                    id: 'SDFSFSFSDFSDFSF',
                    name: 'BvMenu',
                    amount: 0
                },
                meatlessMenu: {
                    id: 'adfgeargheah',
                    name: 'MeatlessMenu',
                    description: 'MeatlessMenu description',
                    price: 8,
                    amount: 0
                },
                dinner: {
                    id: '23f2342343f23f',
                    name: 'Dinner',
                    description: 'Dinner description',
                    price: 10,
                    amount: 0
                },
                dessert: {
                    id: '2fsf23SFSDFSDFf2f',
                    name: 'Dessert',
                    description: 'Dessert description',
                    price: 5,
                    amount: 0
                }
            },
            {
                date: '2024-08-13',
                bvMenu: {
                    id: 'efwf2f2r2f2f2f2f',
                    name: 'BvMenu',
                    amount: 0
                },
                meatlessMenu: {
                    id: '2',
                    name: 'MeatlessMenu',
                    description: 'MeatlessMenu description',
                    price: 8,
                    amount: 0
                },
                dinner: {
                    id: '3',
                    name: 'Dinner',
                    description: 'Dinner description',
                    price: 10,
                    amount: 0
                },
                dessert: {
                    id: '3',
                    name: 'Dessert',
                    description: 'Dessert description',
                    price: 5,
                    amount: 0
                }
            }
        ],
    },
    {
        weekNumber: 34,
        year: 2024,
        days: [
            {
                date: '2024-08-19',
                bvMenu: {
                    id: '1',
                    name: 'BvMenu',
                    amount: 0
                },
                meatlessMenu: {
                    id: '2',
                    name: 'MeatlessMenu',
                    description: 'MeatlessMenu description',
                    price: 8,
                    amount: 0
                },
                dinner: {
                    id: '3',
                    name: 'Dinner',
                    description: 'Dinner description',
                    price: 10,
                    amount: 0
                },
                dessert: {
                    id: '3',
                    name: 'Dessert',
                    description: 'Dessert description',
                    price: 5,
                    amount: 0
                }
            }
        ]
    }
];